config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :boats do
    resources :bookings, only: [:new, :create, :index, :update, :edit]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :bookings, only: [:show, :destroy]
  get "mybookings", to: "bookings#my_bookings"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/boat.rb
class Boat < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :bookings, dependent: :destroy
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  validates :category, :name, :capacity, :location, :price, :rating, presence: true
  validates :category, inclusion: { in: ["Luxury", "Fishing", "Sailing", "Superyacht", "River Boat", "Speedboat", "Houseboat", "Banana Boat"] }
  include PgSearch::Model
  pg_search_scope :search_by_category,
    against: [ :category ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end


# Boat.create!(user: u, category: "Luxury", location: "16 Villa Gaudelet, Paris", price: 1000, name: "Leboat", capacity: 10, rating: 5)

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :boat

  validates :start_date, :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
  end
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  def index
    @boats = Boat.where(user: current_user)
  end

  def show
    @boat = Boat.find(params[:id])
    @markers = [{
        lat: @boat.latitude,
        lng: @boat.longitude
      }]
  end

  def new
    @boat = Boat.new
  end

  def create
    @boat = Boat.new(boat_params)
    @boat.user = current_user
    @boat.save
    redirect_to boats_path
  end

  def edit
    @boat = Boat.find(params[:id])
  end

  def update
    @boat = Boat.find(params[:id])
    if @boat.update(boat_params)
      redirect_to boat_path(@boat)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @boat = Boat.find(params[:id])
    @boat.destroy
    redirect_to boats_path, status: :see_other
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :category, :available, :capacity, :location, :price, :rating, :photo)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_boat, only: [:new, :create, :edit, :update]

  def index
    @bookings = Booking.all
  end

  def new
    @boat = Boat.find(params[:boat_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.boat = @boat
    @booking.user = current_user
    if @booking.save
      redirect_to mybookings_path
    else
      render :new
    end
  end

  def my_bookings
    @bookings = Booking.where(user: current_user)
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to mybookings_path, notice: "Your booking has been updated!"
    else
      render :edit, status: :unprocessible_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def destroy
    # raise
    @booking = Booking.find(params[:id])
    @boat = @booking.boat
    @booking.destroy
    redirect_to boat_path(@boat), status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_boat
    @boat = Boat.find(params[:boat_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    if params[:query].present? && @boats = Boat.search_by_category(params[:query]) != []
      @boats = Boat.search_by_category(params[:query])
    else
      @boats = Boat.all
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boats/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow-sm" style="background-image:url(<%= image_url('form-4.jpg') %>">
      <%= simple_form_for @boat do |f| %>
  <%= f.input :name %>
  <%= f.input :category %>
  <%= f.input :available %>
  <%= f.input :capacity %>
  <%= f.input :location %>
  <%= f.input :price %>
  <%= f.input :rating, required: true, placeholder: '' %>
  <%= f.input :photo, as: :file %>
  <%= f.submit :class => "btn btn-ghost" %>
<% end %>
      </div>
    </div>
  </div>
</div>

app/views/boats/index.html.erb
<div class="container">
<br>
<h1> Welcome, <%= current_user.name %>!</h1>
    <p> <%= button_to("Edit your profile", edit_user_registration_path(current_user), method: :get, :class => "btn btn-ghost") %>
    </p>
          <br>
        <% if @boats.any? %>
          <h2>Your Boats:</h2>
            <br>
              <ul class="list-group mb-3">
                  <div class="row">
                    <% @boats.each do |boat| %>
                    <div class="col-md-4">
                      <%= link_to boat_path(boat) do%>
                        <div class="card card-01">
                          <% if boat.photo.attached? %>
                          <%=cl_image_tag boat.photo.key %>
                          <% else %>
                          <%= image_tag "#{boat.category.parameterize}.jpg", class: "card-img-top" %>
                          <% end %>
                          <div class="card-body">
                            <h4 class="card-title">Name: <%= boat.name %></h4>
                            <p class="card-text">Category: <%= boat.category %></p>
                            <p class="card-text">Location: <%= boat.location %></p>
                            <p class="card-text">
                            Rating:
                            <%  boat.rating.times do  %>
                              <i class="bi bi-star-fill"></i>
                            <% end %>
                            </p>
                            <div align="right">
                            <%= link_to boat_path(boat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                                <i class="fa-solid fa-trash-can" ></i>
                                  <% end %>
                            </div>
                          </div>
                        </div>
                      </div>
                      <% end %>
                      <% end %>
                    </div>
                  </div>
                <% else %>
                <h2> You currently don't have any boats registered with us!</h2>
                <% end %>
          </ul>
        <br>
        <div align="center">
          <%= link_to "Add a new Boat Listing", new_boat_path, class: 'btn btn-ghost' %>
          </div>
        <br>
      </div>
    </div>
  </div>

app/views/boats/new.html.erb
<div class="container py-5">
  <div class="row">>
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow-sm" style="background-image:url(<%= image_url('form-4.jpg') %>">
        <h3>Create a new boat listing!</h3>
        <%= simple_form_for @boat do |f| %>
          <%= f.input :name, required: true, placeholder: 'Queen Elizabeth' %>
          <%= f.input :category, :collection => ["Luxury", "Fishing", "Sailing", "Superyacht", "River Boat", "Speedboat", "Houseboat", "Banana Boat"], prompt: "Add a category" %>
          <%= f.input :capacity, required: true, placeholder: 'XX tonnes' %>
          <%= f.input :location, required: true, placeholder: 'Bournemouth', label: "Address" %>
          <%= f.input :price, required: true, placeholder: '' %>
          <%= f.input :rating, required: true, placeholder: '' %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn btn-ghost' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/boats/show.html.erb
<div class="container_2">
<div class="card-trip">
<% if @boat.photo.attached? %>
  <%= cl_image_tag @boat.photo.key %>
<% else %>
  <%= image_tag "#{@boat.category.parameterize}.jpg" %>
 <% end %>

  <div class="card-trip-main-infos">
    <div class="card-trip-infos">
      <h2><%= @boat.name  %></h2>
      <h2> <i> <%= @boat.category %> </i></h2>
      <p> Available: <%= @boat.available %></p>
      <p> Capacity: <%= @boat.capacity %></p>
      <p> Location: <%= @boat.location %></p>
      <p> Rating: <%= @boat.rating %></p>
    </div>
    <% if @boat.user.photo.attached? %>
      <%= cl_image_tag @boat.user.photo.key, class: "card-trip-user avatar-bordered" %>
    <% else %>
      <%= image_tag "defult-profile-1.jpg", class: "card-trip-user -bordered" %>
    <% end %>
    <div>
      <h2 class="card-trip-pricing">£<%= @boat.price %> per week</h2>
      <% if @boat.user == current_user %>
      <%= link_to "Edit", edit_boat_path(@boat), class: "btn btn-ghost" %>
      <% else %>
       <%= link_to "Book now", boat_path + '/bookings/new', class: "btn btn-ghost" %>
      <% end %>
        <%= link_to "Back to all boats", root_path, class: "btn btn-ghost" %>
    </div>
  </div>
</div>
  <div style="width: 500px; height: 525px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/bookings/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow" style="color: black;">
        <h3>Edit this booking!</h3>
        <%= simple_form_for [@boat, @booking] do |f| %>
          <%= f.input :start_date, required: true %>
          <%= f.input :end_date, required: true %>
          <%= f.submit class: 'btn btn-ghost' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>All Bookings on this Boat</h1>
      <ul class="list-group mb-3">
        <% @bookings.each do |booking| %>
          <li class="list-group-item">
            <%= link_to booking.start_date, booking_path(booking) %>
          </li>
        <% end %>
      </ul>
      <%= link_to "See all boats", boats_path, class: 'btn btn-ghost' %>
    </div>
  </div>
</div>

app/views/bookings/my_bookings.html.erb
<div class="container">
  <% if @bookings.any? %>
    <br>
    <h2>Your bookings:</h2>
    <br>
    <div>
      <ul class="list-group mb-3" >
        <div class="row" >
          <% @bookings.each do |booking| %>
            <div class="col-md-4">
              <%= link_to booking_path(booking) do%>
                <div class="card card-01">
                  <% if booking.boat.photo.attached? %>
                    <%=cl_image_tag booking.boat.photo.key %>
                  <% else %>
                    <%= image_tag "#{booking.boat.category.parameterize}.jpg", class: "card-img-top" %>
                  <% end %>
                  <div class="card-body">
                    <h4 class="card-title">Name: <%= booking.boat.name %></h4>
                    <p class="card-text">Category: <%= booking.boat.category %></p>
                    <p class="card-text">Location: <%= booking.boat.location %></p>
                    <p class="card-text">Rating:
                      <%  booking.boat.rating.times do  %>
                        <i class="bi bi-star-fill"></i>
                      <% end %>
                    </p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </ul>
    </div>
  <% else %>
    <br>
    <h2> You don't have any current bookings!</h2>
    <br>
  <% end %>
  <div align="center">
    <%= link_to "Search all available boats", root_path, :class => 'btn btn-ghost' %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow" style="color: black;">
        <h3>Book this boat!</h3>
        <%= simple_form_for [@boat, @booking] do |f| %>
          <%= f.input :start_date, required: true %>
          <%= f.input :end_date, required: true %>
          <%= f.submit class: 'btn btn-ghost' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container" align="center">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <br>
        <h1>Your booking</h1>
          <br>
            <div class="card disabled" >
              <% if @booking.boat.photo.attached? %>
                <%=cl_image_tag booking.boat.photo.key %>
              <% else %>
                <%= image_tag "#{@booking.boat.category.parameterize}.jpg", class: "card-img-top" %>
              <% end %>
                  <table class="table">
                    <tbody>
                      <tr>
                        <th scope="row">Start Date</th>
                        <td><%= @booking.start_date %></td>
                      </tr>
                      <tr>
                        <th scope="row">End Date</th>
                        <td><%= @booking.end_date %></td>
                      </tr>
                      <tr>
                        <th scope="row">Location</th>
                        <td><%= @booking.boat.location %></td>
                      </tr>
                    </tbody>
                  </table>
              </div>
      </div>
            <div align="center">
              <li class="list-group-item">
                <%= button_to("Edit your booking", edit_boat_booking_path(@booking.boat, @booking), method: "get", :class => "btn btn-ghost")%>
                  <br>
                <%= button_to("Delete booking", booking_path(@booking), method: "delete", :class => "btn btn-ghost")%>
                  <br>
                <%= button_to("See all of your bookings", mybookings_path, method: "get", :class => "btn btn-ghost") %>
                </li>
            </div>
</div>

<%# edit_boat_booking_path([@boat @booking]) %>
<%# boat_path(@boat) + booking_path(@booking) + "/edit" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Air B n Boats</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true  %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
  </head>

  <body>
  <div class='home-container'>
      <%= render 'shared/header' %>
    <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= render 'shared/footer' %>
  </div>
  </body>

</html>

app/views/pages/home.html.erb
       <section>
        <div class="container">
          <div class="row">
          <% @boats.each do |boat| %>
            <div class="col-md-4">
            <%= link_to boat_path(boat) do %>
              <div class="card card-01">
              <% if boat.photo.attached? %>
                <%=cl_image_tag boat.photo.key %>
              <% else %>
                <%= image_tag "#{boat.category.parameterize}.jpg", class: "card-img-top" %>
              <% end %>
                  <div class="card-body">
                    <span class="badge-box"><i class="fa fa-check"></i></span>
                    <h4 class="card-title">Name: <%= boat.name %></h4>
                    <p class="card-text">Category: <%= boat.category %></p>
                    <p class="card-text">Location: <%= boat.location %></p>
                    <p class="card-text">
                    Rating:
                    <%  boat.rating.times do  %>
                      <i class="bi bi-star-fill"></i>
                    <% end %>
                    </p>
                    <p> Owner: <%= boat.user.name %></p>
                  </div>
              </div>
            <% end %>
            </div>
          <% end %>
          </div>
          </div>
        </div>
      </section>

app/views/shared/_avatar-drop-down.htm.erb
          <li class="nav-item dropdown">
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <%= link_to "Profile", "#", class: "dropdown-item" %>
              <%= link_to "Bookings", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
           </li>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Air B-n-Boats
  </div>
</div>

app/views/shared/_header.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon py-0">
  <div class="container-fluid">
    <div class="wrapper">
      <div class="first">
        <%= image_tag "newlogo.png", class: "logo" %>
      </div>
      <div class="second">
        <%= form_with url: root_path , method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find your boat"
          %>
          <%= submit_tag "Search", class: "btn btn-ghost" %>
        <% end %>
      </div>
    </div>
    <div class="title">
    <h1>AIR B-N-BOATS</h1>
    <p>fishing trips, river tours, luxury boating experience</p>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>

          <% unless current_user %>
           <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %> </li>
          <% else %>
           <li class="nav-item dropdown">
           <% if current_user.photo.attached? %>
           <%=cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
           <% else %>
            <%= image_tag "defult-profile-1.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
           <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", boats_path, class: "dropdown-item" %>
              <%= link_to "Bookings", mybookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
           </li>
          <% end%>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete},
  class: "dropdown-item" %>